name: Deploy to Maven Central (manual artifacts)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check artifacts
        run: |
          ls target/ods-corba-api-*.jar
          ls target/ods-corba-api-*-sources.jar
          ls target/ods-corba-api-*-javadoc.jar
          ls target/ods-corba-api-*.pom

      - name: Set up Maven
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven
          server-username: MAVEN_USER
          server-password: MAVEN_PW
          server-id: central

      - name: Release package to Maven central
        env:
          MAVEN_USER: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PW: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_KEY: ${{ secrets.GPG_SECRET_KEY }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}
        run: mvn deploy -Prelease -DskipTests
