name: Deploy to Maven Central (prebuilt artifacts)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g. 1.0.0)'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check artifacts
        run: |
          ls target/ods-corba-api-*.jar
          ls target/ods-corba-api-*-sources.jar
          ls target/ods-corba-api-*-javadoc.jar
          ls target/ods-corba-api-*.pom

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven
          server-username: MAVEN_USER
          server-password: MAVEN_PW
          server-id: central

      - name: Deploy prebuilt artifacts to Maven Central
        run: |
          mvn deploy:deploy-file \
            -Durl=https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/ \
            -DrepositoryId=central \
            -Dfile=target/ods-corba-api-${{ github.event.inputs.version }}.jar \
            -DpomFile=target/ods-corba-api-${{ github.event.inputs.version }}.pom \
            -Dsources=target/ods-corba-api-${{ github.event.inputs.version }}-sources.jar \
            -Djavadoc=target/ods-corba-api-${{ github.event.inputs.version }}-javadoc.jar \
            -Dfiles=target/ods-corba-api-${{ github.event.inputs.version }}.jar.asc,target/ods-corba-api-${{ github.event.inputs.version }}.pom.asc,target/ods-corba-api-${{ github.event.inputs.version }}-sources.jar.asc,target/ods-corba-api-${{ github.event.inputs.version }}-javadoc.jar.asc \
            -Dclassifiers=jar.asc,pom.asc,sources.jar.asc,javadoc.jar.asc \
            -Dtypes=asc,asc,asc,asc
        env:
          MAVEN_USER: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PW: ${{ secrets.OSSRH_PASSWORD }}
